---
title: Ultrafast Optics 2017
email: info@ultrafastoptics-2017.org
description: > # this means to ignore newlines until "baseurl:"
  The Ultrafast Optics 2017 conference will run from October 8-13, 2017.
  Submissions and registration will be opening soon.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - octopress-autoprefixer
exclude:
  - Gemfile
  - Gemfile.lock
